Refactoring config files

diff --git a/env b/env
--- a/env
+++ b/env
@@ -10,6 +10,26 @@ function echo-ok    { printf "\r\033[2K\033[0;32m[ OK ]\033[0m %s\n" "$*"; }
 function echo-fail  { printf "\r\033[2K\033[0;31m[FAIL]\033[0m %s\n" "$*"; }
 
 
+info () {
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+}
+
+user () {
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+}
+
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+
+
 # Library
 function _os {
   case $OSTYPE in
@@ -19,6 +39,14 @@ function _os {
     darwin*) echo macos ;;
     cygwin*) echo cygwin ;;
   esac
+}
+
+# OS detection
+function is_osx() {
+  [[ "$OSTYPE" =~ ^darwin ]] || return 1
+}
+function is_ubuntu() {
+  [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] || return 1
 }
 
 
@@ -36,5 +64,11 @@ function _load {
 function _load_all {
   for file in "$DOTFILES"/**/"$1"; do
     [[ -e $file ]] && source "$file"
+  done
+}
+
+function get_os() {
+  for os in osx ubuntu; do
+    is_$os; [[ $? == ${1:-0} ]] && echo $os
   done
 }
